# .readthedocs.yml
version: 2
build:
  os: ubuntu-20.04
  jobs:
    pre_install:
        # see https://github.com/readthedocs/readthedocs.org/issues/8201
      - git update-index --assume-unchanged ci/requirements/docs.yml docs/conf.py
      # install py-cordex, needs to be editable
      - pip install -e .
  tools:
    python: mambaforge-4.10
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
conda:
  environment: ci/requirements/docs.yml
formats:
  - epub
  - pdf
