name: linting
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: linting
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        # python versions
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags.

      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-downloads-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}"
          environment-file: ci/requirements/environment.yml
          create-args: >-
            python=${{ matrix.python-version }}
            black
            isort
            flake8

      - name: Install py-cordex
        run: |
          python -m pip install --no-deps -e .
      - name: Version info
        run: |
          conda info -a
          conda list
      - name: Import cordex
        run: |
          python -c "import cordex"
      - name: isort
        run: isort --check .
      - name: black
        if: always()
        run: black --check .
      - name: flake8
        if: always()
        run: flake8 .
